baseURL = "https://nomnom-poke-shop.netlify.com/"
description = "This domain is established to be used for illustrative examples in documents. You may use this domain in examples without prior coordination or asking for permission."
languageCode = "en-us"
theme = "site-theme"
title = "Nom Nom Poke Shop"
[[menu.desktop_left]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.desktop_left]]
identifier = "Restaurant"
name = "Restaurant"
url = "/#restaurant-info"
weight = 2
[[menu.desktop_right]]
identifier = "Menu"
name = "Menu"
url = "/#menu-for-restaurant"
weight = 1
[[menu.desktop_right]]
identifier = "learn-more"
name = "Learn More"
url = "/#footer"
weight = 2
[[menu.mobile]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.mobile]]
identifier = "Restaurant"
name = "Restaurant"
url = "/#restaurant-info"
weight = 2
[[menu.mobile]]
identifier = "Menu"
name = "Menu"
url = "/#menu"
weight = 3
[[menu.mobile]]
identifier = "drinks"
name = "Drinks"
url = "/#drinks"
weight = 4
[[menu.mobile]]
identifier = "Reservations"
name = "Reservations"
url = "/#reservations"
weight = 5
[[menu.mobile]]
identifier = "ReadMe"
name = "ReadMe"
url = "/#readme"
weight = 6
[params.Contact_Numbers]
Fax = "555.555.5555"
Phone = "555.555.5555"
[params.Logos]
dark_logo = "/pageimg/default-logo.png"
logo = "/pageimg/Logo4@4x.png"
mobile_menu_logo = "/pageimg/Logo3@4x.png"
[params.address]
city = "Statesboro"
state = "GA"
street = "P.O. Box 134"
zip = 30459
[params.email]
email = "example@example.com"
[params.tracking]
google_analytics = ""
cloudinary_url = ""
[params.social_links]
facebook = ""
insta = ""
linkedin = ""
pinterest = ""