baseURL = "https://nomnom-poke-shop.netlify.com/"
languageCode = "en-us"
theme = "site-theme"
title = "Nom Nom Poke Shop"
enableRobotsTXT = "true"
[params.Meta]
    description = ""
    [[menu.desktop_left]]
        identifier = "about-the-restaurant"
        name = "About the Restaurant"
        url = "#aboutTheRestaurant"
        post = "anchor link"
        weight = 1
    [[menu.desktop_left]]
        identifier = "menu"
        name = "Menu"
        url = "#menuForRestaurant"
        post = "anchor link"
        weight = 2
    [[menu.desktop_right]]
        identifier = "catering"
        name = "Catering"
        url = "#cateringMenu"
        post = "anchor link"
        weight = 1
    [[menu.desktop_right]]
        identifier = "catering"
        name = "Catering"
        url = "#cateringMenu"
        post = "anchor link"
        weight = 2
    [[menu.mobile]]
        identifier = "about-the-restaurant"
        name = "About the Restaurant"
        url = "#aboutTheRestaurant"
        post = "anchor link"
        weight = 1
    [[menu.mobile]]
        identifier = "Restaurant"
        name = "Restaurant"
        url = "#restaurantInfo"
        post = "anchor link"
        weight = 2
    [[menu.mobile]]
        identifier = "Menu"
        name = "Menu"
        url = "#menuForRestaurant"
        post = "anchor link"
        weight = 3
    [[menu.mobile]]
        identifier = "Catering"
        name = "Catering"
        url = "#cateringMenu"
        post = "anchor link"
        weight = 6
[params.address]
    city = "Savannah"
    state = "GA"
    street = "1821 Bull St."
    zip = 31401
[params.contactNumbers]
    Fax = "555.555.5555"
    Phone = "(912) 777-4074"
[params.email]
    email = "nomnompokesav@gmail.com"
[params.Logos]
    logo = "/v1562079194/NomNom%20Poke%20Shop/Logo4_4x.png"
    mobileMenuLogo = "/v1562079194/NomNom%20Poke%20Shop/Logo3_4x.png"
[params.media]
    cloudinaryURL = "https://res.cloudinary.com/animated-eagle/image/upload"
[params.tracking]
    googleAnalytics = ""
[params.publishingSettings]
    siteInProduction = false

[sitemap]
    filename = "sitemap.xml"

[mediaTypes]
  [mediaTypes."text/noExt"]
    suffixes = ""

[outputFormats]
    [outputFormats.sitemap]
        baseName = "sitemap"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.redirects]
        baseName = "_redirects"
        isPlainText = true
        mediaType = "text/noExt"
        path = "/"

[outputs]
    home = ["HTML", "sitemap", "RSS", "redirects"]